alter table tal_member
add MEMBER_POINT NUMBER;


  CREATE TABLE "C##SPRING02"."TAL_MEMBER" 
   (	
   	"MEMBER_ID" VARCHAR2(100 BYTE), 
	"MEMBER_PW" VARCHAR2(100 BYTE), 
	"MEMBER_NAME" VARCHAR2(100 BYTE), 
	"NICKNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"FAVORITE" VARCHAR2(100 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate, 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"MEMBER_TEL" VARCHAR2(100 BYTE), 
	"MEMBER_POINT" NUMBER
   )
   
   